# Name of your blog (this will show up in the RSS feed)
name: Open Twin Cities

# Short description (will also be used in the RSS feed)
# Doubles as OTC's Mission statement
description: A group for civic hackers, innovative government employees, and concerned citizens for the Twin Cities (Minneapolis and Saint Paul) metro area.  Focusing, but not limited to, on creating a better citizen and government collaborative experience in the Twin Cities through technology.  Associated with the Code for America Brigade.

# Uncomment if you are planning to run the blog in a subdirectory
# Note - if you enable this, and attempt to view your site locally you have to use the baseurl in your local path.
# Example, you must use http://localhost:4000/path/to/blog
#baseurl: /path/to/blog 

# The URL of your actual domain. This will be used to make absolute links in the RSS feed.
url: http://www.opentwincities.org

# Default image that social media platforms should display with a page from this site
social_image: http://www.opentwincities.org/images/logos/otc/otc-o512.png

# Continue compiling even if there are errors. Keep it true, unless troubleshooting.
auto: true

# Makes pretty permalinks. See Jekyll docs for alternatives.
permalink: pretty

# Use a better Markdown parser
markdown: redcarpet

exclude: [vendor]
timezone: nil 

prose:
  siteurl: "http://www.opentwincities.org"
  media: "images"
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "blog"
      - name: "title"
        field:
          element: "text"
          label: "Name of the event"
      - name: "author"
        field:
          element: "text"
          label: "Author"
          help: "HTML can be used to link to the author's online presence"
      - name: "social_image"
        field:
          element: "text"
          label: "Social Image"
          help: "Absolute URL of an image that Facebook/Twitter/G+ should display with this post"
      - name: "tags"
        field:
          element: "multiselect"
          label: "Tags"
          alterable: true
    events/_posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "event"
      - name: "category"
        field:
          element: "hidden"
          value: "Events"
      - name: "title"
        field:
          element: "text"
          label: "Name of the event"
      - name: "rsvp_url"
        field:
          element: "text"
          label: "Registration URL"
          help: "URL either to the page where people can signup (e.g. Meetup or Eventbrite page) or the primary site for the event."
      - name: "venue_name"
        field:
          element: "text"
          label: "Venue Name"
      - name: "venue_location"
        field:
          element: "text"
          label: "Venue Address"
          help: "Include Street Address, City, State Zip"
      - name: "social_image"
        field:
          element: "text"
          label: "Social Image"
          help: "Absolute URL of an image that Facebook/Twitter/G+ should display with this event"
      - name: "related_tag"
        field:
          element: "text"
          label: "Related Tag"
          help: "Posts with this tag will be listed at the bottom of the event page." 
